import logging
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from backend.src.ai.embeddings.gemini_embedding import GeminiEmbeddingService
from backend.src.ai.llm.gemini_llm import GeminiLLMService
from backend.src.ai.rag.chroma_vector_store import ChromaVectorStore
from backend.src.ai.rag.rag_pipeline import RAGPipeline
from backend.src.ai.rag.retriever import KnowledgeBaseRetriever
from backend.src.application.services.report_service import ReportService
from backend.src.domain.entities.user import User
from backend.src.domain.exceptions.document_exceptions import DocumentNotFoundError
from backend.src.domain.exceptions.report_exceptions import ReportGenerationError, ReportNotFoundError
from backend.src.infrastructure.database.session import get_async_db
from backend.src.presentation.api.v1.dependencies import get_current_active_user
from backend.src.presentation.schemas.report_schemas import (
    DocumentSummaryRequest,
    DocumentSummaryResponse,
    ReportListResponse,
    SupportReportRequest,
    SupportReportResponse,
)

logger = logging.getLogger("report_router")

router = APIRouter(prefix="/reports", tags=["Reports & Summaries"])


def get_report_service(session: AsyncSession = Depends(get_async_db)) -> ReportService:
    """Dependency provider building ReportService with Gemini AI and RAG services."""
    embed_service = GeminiEmbeddingService()
    chroma_store = ChromaVectorStore()
    retriever = KnowledgeBaseRetriever(embedding_service=embed_service, vector_store=chroma_store)
    rag_pipeline = RAGPipeline(retriever=retriever)
    llm_service = GeminiLLMService()

    return ReportService(
        session=session,
        llm_service=llm_service,
        rag_pipeline=rag_pipeline,
    )


@router.post(
    "/document-summary",
    response_model=DocumentSummaryResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate structured document summary",
)
async def generate_document_summary(
    request: DocumentSummaryRequest,
    current_user: User = Depends(get_current_active_user),
    report_service: ReportService = Depends(get_report_service),
):
    try:
        return await report_service.generate_document_summary(
            user_id=current_user.id,
            document_id=request.document_id,
        )
    except DocumentNotFoundError as e:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(e))
    except ReportGenerationError as e:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=e.message)


@router.post(
    "/support-report",
    response_model=SupportReportResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate customer support analytics report",
)
async def generate_support_report(
    request: SupportReportRequest,
    current_user: User = Depends(get_current_active_user),
    report_service: ReportService = Depends(get_report_service),
):
    try:
        report_entity = await report_service.generate_support_report(
            user_id=current_user.id,
            topic=request.topic,
            conversation_id=request.conversation_id,
        )
        return SupportReportResponse.model_validate(report_entity)
    except ReportGenerationError as e:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=e.message)


@router.get(
    "",
    response_model=ReportListResponse,
    summary="List all reports generated by user",
)
async def list_reports(
    current_user: User = Depends(get_current_active_user),
    report_service: ReportService = Depends(get_report_service),
):
    reports = await report_service.list_user_reports(user_id=current_user.id)
    items = [SupportReportResponse.model_validate(r) for r in reports]
    return ReportListResponse(items=items, total=len(items))


@router.get(
    "/{report_id}",
    response_model=SupportReportResponse,
    summary="Get report details by ID",
)
async def get_report_by_id(
    report_id: str,
    current_user: User = Depends(get_current_active_user),
    report_service: ReportService = Depends(get_report_service),
):
    try:
        report = await report_service.get_report_by_id(
            user_id=current_user.id,
            report_id=report_id,
        )
        return SupportReportResponse.model_validate(report)
    except ReportNotFoundError as e:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(e))
