import io
import textwrap
from typing import List


class SimplePDFGenerator:
    """Generates standard binary PDF 1.4 executive report documents."""

    @staticmethod
    def generate_pdf(title: str, content: str, author: str = "Enterprise AI Support Platform") -> bytes:
        """Create a valid binary PDF document with executive styling, header, content sections, and page footer."""
        buffer = io.BytesIO()

        # Sanitize and format lines
        lines: List[str] = [
            "============================================================",
            f"  {title.upper()}",
            "============================================================",
            f"Author: {author}",
            "Generated by Enterprise RAG SaaS Analytics Engine",
            "------------------------------------------------------------",
            "",
        ]

        # Wrap content text to max 75 characters per line
        raw_paragraphs = content.split("\n")
        for p in raw_paragraphs:
            if not p.strip():
                lines.append("")
                continue
            wrapped = textwrap.wrap(p, width=75)
            lines.extend(wrapped)

        lines.extend([
            "",
            "------------------------------------------------------------",
            "End of Executive Report — Confidential & Proprietary",
        ])

        # Write standard PDF 1.4 structure
        pdf_stream = []
        pdf_stream.append(b"%PDF-1.4\n")

        # Object 1: Catalog
        pdf_stream.append(b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")

        # Object 2: Pages
        pdf_stream.append(b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n")

        # Build text stream content
        text_ops = [b"BT\n/F1 10 Tf\n12 TL\n50 750 Td\n"]
        for line in lines:
            safe_line = line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
            text_ops.append(f"({safe_line}) T*\n".encode("latin-1", errors="replace"))
        text_ops.append(b"ET\n")

        stream_data = b"".join(text_ops)
        stream_len = len(stream_data)

        # Object 3: Page
        pdf_stream.append(b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n")

        # Object 4: Content Stream
        pdf_stream.append(f"4 0 obj\n<< /Length {stream_len} >>\nstream\n".encode("ascii") + stream_data + b"endstream\nendobj\n")

        # Object 5: Font
        pdf_stream.append(b"5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n")

        # Compute xref
        xref_offsets = [0]
        curr_pos = len(pdf_stream[0])
        for obj in pdf_stream[1:]:
            xref_offsets.append(curr_pos)
            curr_pos += len(obj)

        pdf_stream.append(b"xref\n0 6\n0000000000 65535 f \n")
        for off in xref_offsets[1:]:
            pdf_stream.append(f"{off:010d} 00000 n \n".encode("ascii"))

        pdf_stream.append(f"trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n{curr_pos}\n%%EOF\n".encode("ascii"))

        return b"".join(pdf_stream)
